//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class asoc_personaje_skill
    {
        public int id_asoc { get; set; }
        public int id_personaje { get; set; }
        public int id_skill { get; set; }
        public int usos { get; set; }
    
        public virtual personajes personajes { get; set; }
        public virtual skill skill { get; set; }
    }
}
