//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class clases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clases()
        {
            this.personajes = new HashSet<personajes>();
        }
    
        public int id_clase { get; set; }
        public string clas_nombre { get; set; }
        public Nullable<double> clas_fuerza { get; set; }
        public Nullable<double> clas_inteligencia { get; set; }
        public Nullable<double> clas_sabiduria { get; set; }
        public Nullable<double> clas_agilidad { get; set; }
        public Nullable<double> clas_resistencia { get; set; }
        public Nullable<double> clas_aspecto { get; set; }
        public string clas_descripcion { get; set; }
        public string clas_imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personajes> personajes { get; set; }
    }
}
