//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuentro
    {
        public int id_encuentro { get; set; }
        public int id_party_pj { get; set; }
        public int id_party_mon { get; set; }
    
        public virtual party_cabecera party_cabecera { get; set; }
        public virtual party_mon_cabecera party_mon_cabecera { get; set; }
    }
}
