//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public items()
        {
            this.asoc_personaje_item = new HashSet<asoc_personaje_item>();
        }
    
        public int id_item { get; set; }
        public string item_nombre { get; set; }
        public string item_categoria { get; set; }
        public string item_descripcion { get; set; }
        public string item_bonificacion { get; set; }
        public Nullable<double> item_atk { get; set; }
        public Nullable<double> item_mag_atk { get; set; }
        public Nullable<double> item_def { get; set; }
        public Nullable<double> item_mag_def { get; set; }
        public string item_clasificacion { get; set; }
        public string item_tipo { get; set; }
        public string item_imagen_nombre { get; set; }
        public decimal peso { get; set; }
        public Nullable<int> item_tier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asoc_personaje_item> asoc_personaje_item { get; set; }
    }
}
