//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class mochilas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mochilas()
        {
            this.asoc_personaje_mochila = new HashSet<asoc_personaje_mochila>();
        }
    
        public int id_mochila { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> multiplicador_peso { get; set; }
        public Nullable<int> capacidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asoc_personaje_mochila> asoc_personaje_mochila { get; set; }
    }
}
