//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RollEntities : DbContext
    {
        public RollEntities()
            : base("name=RollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asoc_personaje_item> asoc_personaje_item { get; set; }
        public virtual DbSet<asoc_personaje_skill> asoc_personaje_skill { get; set; }
        public virtual DbSet<atributo> atributo { get; set; }
        public virtual DbSet<clases> clases { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<personajes> personajes { get; set; }
        public virtual DbSet<razas> razas { get; set; }
        public virtual DbSet<skill> skill { get; set; }
        public virtual DbSet<leveleo> leveleo { get; set; }
        public virtual DbSet<monstruos> monstruos { get; set; }
        public virtual DbSet<encuentro> encuentro { get; set; }
        public virtual DbSet<party_mon_cabecera> party_mon_cabecera { get; set; }
        public virtual DbSet<party_mon> party_mon { get; set; }
        public virtual DbSet<party_cabecera> party_cabecera { get; set; }
        public virtual DbSet<party> party { get; set; }
        public virtual DbSet<mochilas> mochilas { get; set; }
        public virtual DbSet<asoc_personaje_mochila> asoc_personaje_mochila { get; set; }
        public virtual DbSet<mascotas> mascotas { get; set; }
    
        public virtual int economia(Nullable<int> id, string tipo, Nullable<int> oro, Nullable<int> plata, Nullable<int> cobre)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var oroParameter = oro.HasValue ?
                new ObjectParameter("oro", oro) :
                new ObjectParameter("oro", typeof(int));
    
            var plataParameter = plata.HasValue ?
                new ObjectParameter("plata", plata) :
                new ObjectParameter("plata", typeof(int));
    
            var cobreParameter = cobre.HasValue ?
                new ObjectParameter("cobre", cobre) :
                new ObjectParameter("cobre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("economia", idParameter, tipoParameter, oroParameter, plataParameter, cobreParameter);
        }
    
        public virtual int estadistica_update_actual(Nullable<int> id, string estadistica, Nullable<int> valor_nuevo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var estadisticaParameter = estadistica != null ?
                new ObjectParameter("estadistica", estadistica) :
                new ObjectParameter("estadistica", typeof(string));
    
            var valor_nuevoParameter = valor_nuevo.HasValue ?
                new ObjectParameter("valor_nuevo", valor_nuevo) :
                new ObjectParameter("valor_nuevo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("estadistica_update_actual", idParameter, estadisticaParameter, valor_nuevoParameter);
        }
    
        public virtual int estadistica_update_real(Nullable<int> id, string estadistica, Nullable<int> valor_nuevo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var estadisticaParameter = estadistica != null ?
                new ObjectParameter("estadistica", estadistica) :
                new ObjectParameter("estadistica", typeof(string));
    
            var valor_nuevoParameter = valor_nuevo.HasValue ?
                new ObjectParameter("valor_nuevo", valor_nuevo) :
                new ObjectParameter("valor_nuevo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("estadistica_update_real", idParameter, estadisticaParameter, valor_nuevoParameter);
        }
    
        public virtual int lvl_up(Nullable<int> id, Nullable<int> fuerza, Nullable<int> inteligencia, Nullable<int> sabiduria, Nullable<int> agilidad, Nullable<int> resistencia, Nullable<int> velocidad)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fuerzaParameter = fuerza.HasValue ?
                new ObjectParameter("fuerza", fuerza) :
                new ObjectParameter("fuerza", typeof(int));
    
            var inteligenciaParameter = inteligencia.HasValue ?
                new ObjectParameter("inteligencia", inteligencia) :
                new ObjectParameter("inteligencia", typeof(int));
    
            var sabiduriaParameter = sabiduria.HasValue ?
                new ObjectParameter("sabiduria", sabiduria) :
                new ObjectParameter("sabiduria", typeof(int));
    
            var agilidadParameter = agilidad.HasValue ?
                new ObjectParameter("agilidad", agilidad) :
                new ObjectParameter("agilidad", typeof(int));
    
            var resistenciaParameter = resistencia.HasValue ?
                new ObjectParameter("resistencia", resistencia) :
                new ObjectParameter("resistencia", typeof(int));
    
            var velocidadParameter = velocidad.HasValue ?
                new ObjectParameter("velocidad", velocidad) :
                new ObjectParameter("velocidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lvl_up", idParameter, fuerzaParameter, inteligenciaParameter, sabiduriaParameter, agilidadParameter, resistenciaParameter, velocidadParameter);
        }
    
        public virtual int personaje_insert(string nombre, Nullable<int> raza, Nullable<int> clase, Nullable<int> atributo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var razaParameter = raza.HasValue ?
                new ObjectParameter("raza", raza) :
                new ObjectParameter("raza", typeof(int));
    
            var claseParameter = clase.HasValue ?
                new ObjectParameter("clase", clase) :
                new ObjectParameter("clase", typeof(int));
    
            var atributoParameter = atributo.HasValue ?
                new ObjectParameter("atributo", atributo) :
                new ObjectParameter("atributo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("personaje_insert", nombreParameter, razaParameter, claseParameter, atributoParameter);
        }
    
        public virtual int personajes_delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("personajes_delete", idParameter);
        }
    
        public virtual int personajes_update(Nullable<int> id, string nombre, Nullable<int> nivel, Nullable<int> raza, Nullable<int> clase, Nullable<int> atributo, Nullable<int> vida_real, Nullable<int> energia_real, Nullable<int> atk, Nullable<int> mag_atk, Nullable<int> armor, Nullable<int> mr, Nullable<int> oro, Nullable<int> plata, Nullable<int> cobre, Nullable<int> vida_actual, Nullable<int> energia_actual, Nullable<int> fuerza_inicial, Nullable<int> fuerza_real, Nullable<int> fuerza_actual, Nullable<int> intel_ini, Nullable<int> intel_real, Nullable<int> intel_actual, Nullable<int> sab_ini, Nullable<int> sab_real, Nullable<int> sab_actual, Nullable<int> agi_ini, Nullable<int> agi_real, Nullable<int> agi_actual, Nullable<int> res_ini, Nullable<int> res_real, Nullable<int> res_actual, Nullable<int> velocidad_ini, Nullable<int> velocidad_real, Nullable<int> velocidad_actual, Nullable<int> estado, Nullable<bool> habilitado, string imagen)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var nivelParameter = nivel.HasValue ?
                new ObjectParameter("nivel", nivel) :
                new ObjectParameter("nivel", typeof(int));
    
            var razaParameter = raza.HasValue ?
                new ObjectParameter("raza", raza) :
                new ObjectParameter("raza", typeof(int));
    
            var claseParameter = clase.HasValue ?
                new ObjectParameter("clase", clase) :
                new ObjectParameter("clase", typeof(int));
    
            var atributoParameter = atributo.HasValue ?
                new ObjectParameter("atributo", atributo) :
                new ObjectParameter("atributo", typeof(int));
    
            var vida_realParameter = vida_real.HasValue ?
                new ObjectParameter("vida_real", vida_real) :
                new ObjectParameter("vida_real", typeof(int));
    
            var energia_realParameter = energia_real.HasValue ?
                new ObjectParameter("energia_real", energia_real) :
                new ObjectParameter("energia_real", typeof(int));
    
            var atkParameter = atk.HasValue ?
                new ObjectParameter("atk", atk) :
                new ObjectParameter("atk", typeof(int));
    
            var mag_atkParameter = mag_atk.HasValue ?
                new ObjectParameter("mag_atk", mag_atk) :
                new ObjectParameter("mag_atk", typeof(int));
    
            var armorParameter = armor.HasValue ?
                new ObjectParameter("armor", armor) :
                new ObjectParameter("armor", typeof(int));
    
            var mrParameter = mr.HasValue ?
                new ObjectParameter("mr", mr) :
                new ObjectParameter("mr", typeof(int));
    
            var oroParameter = oro.HasValue ?
                new ObjectParameter("oro", oro) :
                new ObjectParameter("oro", typeof(int));
    
            var plataParameter = plata.HasValue ?
                new ObjectParameter("plata", plata) :
                new ObjectParameter("plata", typeof(int));
    
            var cobreParameter = cobre.HasValue ?
                new ObjectParameter("cobre", cobre) :
                new ObjectParameter("cobre", typeof(int));
    
            var vida_actualParameter = vida_actual.HasValue ?
                new ObjectParameter("vida_actual", vida_actual) :
                new ObjectParameter("vida_actual", typeof(int));
    
            var energia_actualParameter = energia_actual.HasValue ?
                new ObjectParameter("energia_actual", energia_actual) :
                new ObjectParameter("energia_actual", typeof(int));
    
            var fuerza_inicialParameter = fuerza_inicial.HasValue ?
                new ObjectParameter("fuerza_inicial", fuerza_inicial) :
                new ObjectParameter("fuerza_inicial", typeof(int));
    
            var fuerza_realParameter = fuerza_real.HasValue ?
                new ObjectParameter("fuerza_real", fuerza_real) :
                new ObjectParameter("fuerza_real", typeof(int));
    
            var fuerza_actualParameter = fuerza_actual.HasValue ?
                new ObjectParameter("fuerza_actual", fuerza_actual) :
                new ObjectParameter("fuerza_actual", typeof(int));
    
            var intel_iniParameter = intel_ini.HasValue ?
                new ObjectParameter("intel_ini", intel_ini) :
                new ObjectParameter("intel_ini", typeof(int));
    
            var intel_realParameter = intel_real.HasValue ?
                new ObjectParameter("intel_real", intel_real) :
                new ObjectParameter("intel_real", typeof(int));
    
            var intel_actualParameter = intel_actual.HasValue ?
                new ObjectParameter("intel_actual", intel_actual) :
                new ObjectParameter("intel_actual", typeof(int));
    
            var sab_iniParameter = sab_ini.HasValue ?
                new ObjectParameter("sab_ini", sab_ini) :
                new ObjectParameter("sab_ini", typeof(int));
    
            var sab_realParameter = sab_real.HasValue ?
                new ObjectParameter("sab_real", sab_real) :
                new ObjectParameter("sab_real", typeof(int));
    
            var sab_actualParameter = sab_actual.HasValue ?
                new ObjectParameter("sab_actual", sab_actual) :
                new ObjectParameter("sab_actual", typeof(int));
    
            var agi_iniParameter = agi_ini.HasValue ?
                new ObjectParameter("agi_ini", agi_ini) :
                new ObjectParameter("agi_ini", typeof(int));
    
            var agi_realParameter = agi_real.HasValue ?
                new ObjectParameter("agi_real", agi_real) :
                new ObjectParameter("agi_real", typeof(int));
    
            var agi_actualParameter = agi_actual.HasValue ?
                new ObjectParameter("agi_actual", agi_actual) :
                new ObjectParameter("agi_actual", typeof(int));
    
            var res_iniParameter = res_ini.HasValue ?
                new ObjectParameter("res_ini", res_ini) :
                new ObjectParameter("res_ini", typeof(int));
    
            var res_realParameter = res_real.HasValue ?
                new ObjectParameter("res_real", res_real) :
                new ObjectParameter("res_real", typeof(int));
    
            var res_actualParameter = res_actual.HasValue ?
                new ObjectParameter("res_actual", res_actual) :
                new ObjectParameter("res_actual", typeof(int));
    
            var velocidad_iniParameter = velocidad_ini.HasValue ?
                new ObjectParameter("velocidad_ini", velocidad_ini) :
                new ObjectParameter("velocidad_ini", typeof(int));
    
            var velocidad_realParameter = velocidad_real.HasValue ?
                new ObjectParameter("velocidad_real", velocidad_real) :
                new ObjectParameter("velocidad_real", typeof(int));
    
            var velocidad_actualParameter = velocidad_actual.HasValue ?
                new ObjectParameter("velocidad_actual", velocidad_actual) :
                new ObjectParameter("velocidad_actual", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var habilitadoParameter = habilitado.HasValue ?
                new ObjectParameter("habilitado", habilitado) :
                new ObjectParameter("habilitado", typeof(bool));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("personajes_update", idParameter, nombreParameter, nivelParameter, razaParameter, claseParameter, atributoParameter, vida_realParameter, energia_realParameter, atkParameter, mag_atkParameter, armorParameter, mrParameter, oroParameter, plataParameter, cobreParameter, vida_actualParameter, energia_actualParameter, fuerza_inicialParameter, fuerza_realParameter, fuerza_actualParameter, intel_iniParameter, intel_realParameter, intel_actualParameter, sab_iniParameter, sab_realParameter, sab_actualParameter, agi_iniParameter, agi_realParameter, agi_actualParameter, res_iniParameter, res_realParameter, res_actualParameter, velocidad_iniParameter, velocidad_realParameter, velocidad_actualParameter, estadoParameter, habilitadoParameter, imagenParameter);
        }
    
        public virtual ObjectResult<get_items_Result> get_items(Nullable<int> id_pj, string categoria)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            var categoriaParameter = categoria != null ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_items_Result>("get_items", id_pjParameter, categoriaParameter);
        }
    
        public virtual ObjectResult<get_skills_Result> get_skills(Nullable<int> id_pj)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_skills_Result>("get_skills", id_pjParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> get_lvl_up(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("get_lvl_up", idParameter);
        }
    
        public virtual int skill_delete(Nullable<int> skill_id)
        {
            var skill_idParameter = skill_id.HasValue ?
                new ObjectParameter("skill_id", skill_id) :
                new ObjectParameter("skill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("skill_delete", skill_idParameter);
        }
    
        public virtual int skill_insert(string skill_nombre, Nullable<double> skill_nivel, string skill_tipo, string skill_atributo, Nullable<double> skill_costo, string skill_tipo_efecto, string skill_danio, string skill_dado_basico, string skill_requisito, string skill_alineamiento)
        {
            var skill_nombreParameter = skill_nombre != null ?
                new ObjectParameter("skill_nombre", skill_nombre) :
                new ObjectParameter("skill_nombre", typeof(string));
    
            var skill_nivelParameter = skill_nivel.HasValue ?
                new ObjectParameter("skill_nivel", skill_nivel) :
                new ObjectParameter("skill_nivel", typeof(double));
    
            var skill_tipoParameter = skill_tipo != null ?
                new ObjectParameter("skill_tipo", skill_tipo) :
                new ObjectParameter("skill_tipo", typeof(string));
    
            var skill_atributoParameter = skill_atributo != null ?
                new ObjectParameter("skill_atributo", skill_atributo) :
                new ObjectParameter("skill_atributo", typeof(string));
    
            var skill_costoParameter = skill_costo.HasValue ?
                new ObjectParameter("skill_costo", skill_costo) :
                new ObjectParameter("skill_costo", typeof(double));
    
            var skill_tipo_efectoParameter = skill_tipo_efecto != null ?
                new ObjectParameter("skill_tipo_efecto", skill_tipo_efecto) :
                new ObjectParameter("skill_tipo_efecto", typeof(string));
    
            var skill_danioParameter = skill_danio != null ?
                new ObjectParameter("skill_danio", skill_danio) :
                new ObjectParameter("skill_danio", typeof(string));
    
            var skill_dado_basicoParameter = skill_dado_basico != null ?
                new ObjectParameter("skill_dado_basico", skill_dado_basico) :
                new ObjectParameter("skill_dado_basico", typeof(string));
    
            var skill_requisitoParameter = skill_requisito != null ?
                new ObjectParameter("skill_requisito", skill_requisito) :
                new ObjectParameter("skill_requisito", typeof(string));
    
            var skill_alineamientoParameter = skill_alineamiento != null ?
                new ObjectParameter("skill_alineamiento", skill_alineamiento) :
                new ObjectParameter("skill_alineamiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("skill_insert", skill_nombreParameter, skill_nivelParameter, skill_tipoParameter, skill_atributoParameter, skill_costoParameter, skill_tipo_efectoParameter, skill_danioParameter, skill_dado_basicoParameter, skill_requisitoParameter, skill_alineamientoParameter);
        }
    
        public virtual int skill_update(Nullable<int> skill_id, string skill_nombre, Nullable<double> skill_nivel, string skill_tipo, string skill_atributo, Nullable<double> skill_costo, string skill_tipo_efecto, string skill_danio, string skill_dado_basico, string skill_requisito, string skill_alineamiento)
        {
            var skill_idParameter = skill_id.HasValue ?
                new ObjectParameter("skill_id", skill_id) :
                new ObjectParameter("skill_id", typeof(int));
    
            var skill_nombreParameter = skill_nombre != null ?
                new ObjectParameter("skill_nombre", skill_nombre) :
                new ObjectParameter("skill_nombre", typeof(string));
    
            var skill_nivelParameter = skill_nivel.HasValue ?
                new ObjectParameter("skill_nivel", skill_nivel) :
                new ObjectParameter("skill_nivel", typeof(double));
    
            var skill_tipoParameter = skill_tipo != null ?
                new ObjectParameter("skill_tipo", skill_tipo) :
                new ObjectParameter("skill_tipo", typeof(string));
    
            var skill_atributoParameter = skill_atributo != null ?
                new ObjectParameter("skill_atributo", skill_atributo) :
                new ObjectParameter("skill_atributo", typeof(string));
    
            var skill_costoParameter = skill_costo.HasValue ?
                new ObjectParameter("skill_costo", skill_costo) :
                new ObjectParameter("skill_costo", typeof(double));
    
            var skill_tipo_efectoParameter = skill_tipo_efecto != null ?
                new ObjectParameter("skill_tipo_efecto", skill_tipo_efecto) :
                new ObjectParameter("skill_tipo_efecto", typeof(string));
    
            var skill_danioParameter = skill_danio != null ?
                new ObjectParameter("skill_danio", skill_danio) :
                new ObjectParameter("skill_danio", typeof(string));
    
            var skill_dado_basicoParameter = skill_dado_basico != null ?
                new ObjectParameter("skill_dado_basico", skill_dado_basico) :
                new ObjectParameter("skill_dado_basico", typeof(string));
    
            var skill_requisitoParameter = skill_requisito != null ?
                new ObjectParameter("skill_requisito", skill_requisito) :
                new ObjectParameter("skill_requisito", typeof(string));
    
            var skill_alineamientoParameter = skill_alineamiento != null ?
                new ObjectParameter("skill_alineamiento", skill_alineamiento) :
                new ObjectParameter("skill_alineamiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("skill_update", skill_idParameter, skill_nombreParameter, skill_nivelParameter, skill_tipoParameter, skill_atributoParameter, skill_costoParameter, skill_tipo_efectoParameter, skill_danioParameter, skill_dado_basicoParameter, skill_requisitoParameter, skill_alineamientoParameter);
        }
    
        public virtual int skill_up_use(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("skill_up_use", idParameter);
        }
    
        public virtual ObjectResult<get_skills_listado_resumido_Result> get_skills_listado_resumido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_skills_listado_resumido_Result>("get_skills_listado_resumido");
        }
    
        public virtual int crear_asignacion_skill(Nullable<int> id_personaje, Nullable<int> id_skill)
        {
            var id_personajeParameter = id_personaje.HasValue ?
                new ObjectParameter("id_personaje", id_personaje) :
                new ObjectParameter("id_personaje", typeof(int));
    
            var id_skillParameter = id_skill.HasValue ?
                new ObjectParameter("id_skill", id_skill) :
                new ObjectParameter("id_skill", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crear_asignacion_skill", id_personajeParameter, id_skillParameter);
        }
    
        public virtual int crear_asignacion_item(Nullable<int> id_personaje, Nullable<int> id_item, Nullable<int> cantidad, Nullable<bool> equipado)
        {
            var id_personajeParameter = id_personaje.HasValue ?
                new ObjectParameter("id_personaje", id_personaje) :
                new ObjectParameter("id_personaje", typeof(int));
    
            var id_itemParameter = id_item.HasValue ?
                new ObjectParameter("id_item", id_item) :
                new ObjectParameter("id_item", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var equipadoParameter = equipado.HasValue ?
                new ObjectParameter("equipado", equipado) :
                new ObjectParameter("equipado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crear_asignacion_item", id_personajeParameter, id_itemParameter, cantidadParameter, equipadoParameter);
        }
    
        public virtual int equip_un(Nullable<int> id_asoc)
        {
            var id_asocParameter = id_asoc.HasValue ?
                new ObjectParameter("id_asoc", id_asoc) :
                new ObjectParameter("id_asoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("equip_un", id_asocParameter);
        }
    
        public virtual int buff_up(Nullable<int> id, Nullable<int> fuerza, Nullable<int> inteligencia, Nullable<int> sabiduria, Nullable<int> agilidad, Nullable<int> resistencia, Nullable<int> velocidad)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fuerzaParameter = fuerza.HasValue ?
                new ObjectParameter("fuerza", fuerza) :
                new ObjectParameter("fuerza", typeof(int));
    
            var inteligenciaParameter = inteligencia.HasValue ?
                new ObjectParameter("inteligencia", inteligencia) :
                new ObjectParameter("inteligencia", typeof(int));
    
            var sabiduriaParameter = sabiduria.HasValue ?
                new ObjectParameter("sabiduria", sabiduria) :
                new ObjectParameter("sabiduria", typeof(int));
    
            var agilidadParameter = agilidad.HasValue ?
                new ObjectParameter("agilidad", agilidad) :
                new ObjectParameter("agilidad", typeof(int));
    
            var resistenciaParameter = resistencia.HasValue ?
                new ObjectParameter("resistencia", resistencia) :
                new ObjectParameter("resistencia", typeof(int));
    
            var velocidadParameter = velocidad.HasValue ?
                new ObjectParameter("velocidad", velocidad) :
                new ObjectParameter("velocidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("buff_up", idParameter, fuerzaParameter, inteligenciaParameter, sabiduriaParameter, agilidadParameter, resistenciaParameter, velocidadParameter);
        }
    
        public virtual int agregar_a_la_party(Nullable<int> id_party, Nullable<int> id_personaje)
        {
            var id_partyParameter = id_party.HasValue ?
                new ObjectParameter("id_party", id_party) :
                new ObjectParameter("id_party", typeof(int));
    
            var id_personajeParameter = id_personaje.HasValue ?
                new ObjectParameter("id_personaje", id_personaje) :
                new ObjectParameter("id_personaje", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("agregar_a_la_party", id_partyParameter, id_personajeParameter);
        }
    
        public virtual int agregar_a_la_party_mon(Nullable<int> id_party, Nullable<int> id_mon, Nullable<int> estado)
        {
            var id_partyParameter = id_party.HasValue ?
                new ObjectParameter("id_party", id_party) :
                new ObjectParameter("id_party", typeof(int));
    
            var id_monParameter = id_mon.HasValue ?
                new ObjectParameter("id_mon", id_mon) :
                new ObjectParameter("id_mon", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("agregar_a_la_party_mon", id_partyParameter, id_monParameter, estadoParameter);
        }
    
        public virtual int eliminar_miembro_party_mon(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("eliminar_miembro_party_mon", idParameter);
        }
    
        public virtual int modificar_miembro_party_mon(Nullable<int> id, Nullable<int> vida_resta, Nullable<int> mana_resta, Nullable<int> estado)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var vida_restaParameter = vida_resta.HasValue ?
                new ObjectParameter("vida_resta", vida_resta) :
                new ObjectParameter("vida_resta", typeof(int));
    
            var mana_restaParameter = mana_resta.HasValue ?
                new ObjectParameter("mana_resta", mana_resta) :
                new ObjectParameter("mana_resta", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modificar_miembro_party_mon", idParameter, vida_restaParameter, mana_restaParameter, estadoParameter);
        }
    
        public virtual int descontar_mana_mon(Nullable<int> id_party_mon_id, Nullable<int> mana)
        {
            var id_party_mon_idParameter = id_party_mon_id.HasValue ?
                new ObjectParameter("id_party_mon_id", id_party_mon_id) :
                new ObjectParameter("id_party_mon_id", typeof(int));
    
            var manaParameter = mana.HasValue ?
                new ObjectParameter("mana", mana) :
                new ObjectParameter("mana", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("descontar_mana_mon", id_party_mon_idParameter, manaParameter);
        }
    
        public virtual ObjectResult<get_atributos_calculadora_Result> get_atributos_calculadora(Nullable<int> pj_id)
        {
            var pj_idParameter = pj_id.HasValue ?
                new ObjectParameter("pj_id", pj_id) :
                new ObjectParameter("pj_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_atributos_calculadora_Result>("get_atributos_calculadora", pj_idParameter);
        }
    
        public virtual int impactar_danio_a_mon(Nullable<int> id_party_mon_id, Nullable<bool> es_skill, Nullable<int> tipo_danio, Nullable<int> agi_pj, Nullable<int> vel_pj, Nullable<int> danio_pj_basico, Nullable<int> dado_prec, Nullable<int> danio_skill, Nullable<bool> es_magico)
        {
            var id_party_mon_idParameter = id_party_mon_id.HasValue ?
                new ObjectParameter("id_party_mon_id", id_party_mon_id) :
                new ObjectParameter("id_party_mon_id", typeof(int));
    
            var es_skillParameter = es_skill.HasValue ?
                new ObjectParameter("es_skill", es_skill) :
                new ObjectParameter("es_skill", typeof(bool));
    
            var tipo_danioParameter = tipo_danio.HasValue ?
                new ObjectParameter("tipo_danio", tipo_danio) :
                new ObjectParameter("tipo_danio", typeof(int));
    
            var agi_pjParameter = agi_pj.HasValue ?
                new ObjectParameter("agi_pj", agi_pj) :
                new ObjectParameter("agi_pj", typeof(int));
    
            var vel_pjParameter = vel_pj.HasValue ?
                new ObjectParameter("vel_pj", vel_pj) :
                new ObjectParameter("vel_pj", typeof(int));
    
            var danio_pj_basicoParameter = danio_pj_basico.HasValue ?
                new ObjectParameter("danio_pj_basico", danio_pj_basico) :
                new ObjectParameter("danio_pj_basico", typeof(int));
    
            var dado_precParameter = dado_prec.HasValue ?
                new ObjectParameter("dado_prec", dado_prec) :
                new ObjectParameter("dado_prec", typeof(int));
    
            var danio_skillParameter = danio_skill.HasValue ?
                new ObjectParameter("danio_skill", danio_skill) :
                new ObjectParameter("danio_skill", typeof(int));
    
            var es_magicoParameter = es_magico.HasValue ?
                new ObjectParameter("es_magico", es_magico) :
                new ObjectParameter("es_magico", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("impactar_danio_a_mon", id_party_mon_idParameter, es_skillParameter, tipo_danioParameter, agi_pjParameter, vel_pjParameter, danio_pj_basicoParameter, dado_precParameter, danio_skillParameter, es_magicoParameter);
        }
    
        public virtual ObjectResult<select_pj_Result> select_pj(Nullable<int> id_party)
        {
            var id_partyParameter = id_party.HasValue ?
                new ObjectParameter("id_party", id_party) :
                new ObjectParameter("id_party", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_pj_Result>("select_pj", id_partyParameter);
        }
    
        public virtual ObjectResult<get_numeros_pj_calculadora_Result> get_numeros_pj_calculadora(Nullable<int> id_pj)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_numeros_pj_calculadora_Result>("get_numeros_pj_calculadora", id_pjParameter);
        }
    
        public virtual int impactar_danio_a_pj(Nullable<int> id_pj, Nullable<bool> es_skill, Nullable<int> tipo_danio, Nullable<int> tier, Nullable<int> vel_mon, Nullable<int> danio_mon_basico, Nullable<int> dado_prec, Nullable<int> danio_skill, Nullable<bool> es_magico)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            var es_skillParameter = es_skill.HasValue ?
                new ObjectParameter("es_skill", es_skill) :
                new ObjectParameter("es_skill", typeof(bool));
    
            var tipo_danioParameter = tipo_danio.HasValue ?
                new ObjectParameter("tipo_danio", tipo_danio) :
                new ObjectParameter("tipo_danio", typeof(int));
    
            var tierParameter = tier.HasValue ?
                new ObjectParameter("tier", tier) :
                new ObjectParameter("tier", typeof(int));
    
            var vel_monParameter = vel_mon.HasValue ?
                new ObjectParameter("vel_mon", vel_mon) :
                new ObjectParameter("vel_mon", typeof(int));
    
            var danio_mon_basicoParameter = danio_mon_basico.HasValue ?
                new ObjectParameter("danio_mon_basico", danio_mon_basico) :
                new ObjectParameter("danio_mon_basico", typeof(int));
    
            var dado_precParameter = dado_prec.HasValue ?
                new ObjectParameter("dado_prec", dado_prec) :
                new ObjectParameter("dado_prec", typeof(int));
    
            var danio_skillParameter = danio_skill.HasValue ?
                new ObjectParameter("danio_skill", danio_skill) :
                new ObjectParameter("danio_skill", typeof(int));
    
            var es_magicoParameter = es_magico.HasValue ?
                new ObjectParameter("es_magico", es_magico) :
                new ObjectParameter("es_magico", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("impactar_danio_a_pj", id_pjParameter, es_skillParameter, tipo_danioParameter, tierParameter, vel_monParameter, danio_mon_basicoParameter, dado_precParameter, danio_skillParameter, es_magicoParameter);
        }
    
        public virtual int crear_asignacion_mochila(Nullable<int> id_personaje, Nullable<int> id_mochila, Nullable<decimal> peso_ocupado)
        {
            var id_personajeParameter = id_personaje.HasValue ?
                new ObjectParameter("id_personaje", id_personaje) :
                new ObjectParameter("id_personaje", typeof(int));
    
            var id_mochilaParameter = id_mochila.HasValue ?
                new ObjectParameter("id_mochila", id_mochila) :
                new ObjectParameter("id_mochila", typeof(int));
    
            var peso_ocupadoParameter = peso_ocupado.HasValue ?
                new ObjectParameter("peso_ocupado", peso_ocupado) :
                new ObjectParameter("peso_ocupado", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crear_asignacion_mochila", id_personajeParameter, id_mochilaParameter, peso_ocupadoParameter);
        }
    
        public virtual ObjectResult<get_peso_mochila_Result> get_peso_mochila(Nullable<int> id_pj)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_peso_mochila_Result>("get_peso_mochila", id_pjParameter);
        }
    
        public virtual ObjectResult<get_peso_total_Result> get_peso_total(Nullable<int> id_pj)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_peso_total_Result>("get_peso_total", id_pjParameter);
        }
    
        public virtual int eliminar_asignacion_mochila(Nullable<int> id_asoc)
        {
            var id_asocParameter = id_asoc.HasValue ?
                new ObjectParameter("id_asoc", id_asoc) :
                new ObjectParameter("id_asoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("eliminar_asignacion_mochila", id_asocParameter);
        }
    
        public virtual int modificar_asignacion_mochila(Nullable<int> id_asoc, Nullable<int> id_personaje, Nullable<int> id_mochila, Nullable<decimal> peso_ocupado, Nullable<bool> equipado)
        {
            var id_asocParameter = id_asoc.HasValue ?
                new ObjectParameter("id_asoc", id_asoc) :
                new ObjectParameter("id_asoc", typeof(int));
    
            var id_personajeParameter = id_personaje.HasValue ?
                new ObjectParameter("id_personaje", id_personaje) :
                new ObjectParameter("id_personaje", typeof(int));
    
            var id_mochilaParameter = id_mochila.HasValue ?
                new ObjectParameter("id_mochila", id_mochila) :
                new ObjectParameter("id_mochila", typeof(int));
    
            var peso_ocupadoParameter = peso_ocupado.HasValue ?
                new ObjectParameter("peso_ocupado", peso_ocupado) :
                new ObjectParameter("peso_ocupado", typeof(decimal));
    
            var equipadoParameter = equipado.HasValue ?
                new ObjectParameter("equipado", equipado) :
                new ObjectParameter("equipado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modificar_asignacion_mochila", id_asocParameter, id_personajeParameter, id_mochilaParameter, peso_ocupadoParameter, equipadoParameter);
        }
    
        public virtual int equip_un_mochila(Nullable<int> id_pj)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("equip_un_mochila", id_pjParameter);
        }
    
        public virtual ObjectResult<jugadores_con_monedero_Result> jugadores_con_monedero(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<jugadores_con_monedero_Result>("jugadores_con_monedero", idParameter);
        }
    
        public virtual ObjectResult<get_mascotas_Result> get_mascotas(Nullable<int> id_pj)
        {
            var id_pjParameter = id_pj.HasValue ?
                new ObjectParameter("id_pj", id_pj) :
                new ObjectParameter("id_pj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_mascotas_Result>("get_mascotas", id_pjParameter);
        }
    
        public virtual ObjectResult<sugerir_activas_Result> sugerir_activas(Nullable<int> clase_id)
        {
            var clase_idParameter = clase_id.HasValue ?
                new ObjectParameter("clase_id", clase_id) :
                new ObjectParameter("clase_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sugerir_activas_Result>("sugerir_activas", clase_idParameter);
        }
    
        public virtual ObjectResult<sugerir_pasivas_Result> sugerir_pasivas(Nullable<int> clase_id)
        {
            var clase_idParameter = clase_id.HasValue ?
                new ObjectParameter("clase_id", clase_id) :
                new ObjectParameter("clase_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sugerir_pasivas_Result>("sugerir_pasivas", clase_idParameter);
        }
    }
}
