//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class monstruos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public monstruos()
        {
            this.party_mon = new HashSet<party_mon>();
            this.mascotas = new HashSet<mascotas>();
        }
    
        public int mon_id { get; set; }
        public int tier { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int vida { get; set; }
        public int mana { get; set; }
        public string ataque_basico { get; set; }
        public string ataque_especial { get; set; }
        public int velocidad { get; set; }
        public int armor { get; set; }
        public int mr { get; set; }
        public int evasion { get; set; }
        public int experiencia { get; set; }
        public string nombre_imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<party_mon> party_mon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mascotas> mascotas { get; set; }
    }
}
