//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_mon
    {
        public int id_party_mon { get; set; }
        public int id_mon { get; set; }
        public Nullable<int> vida_max { get; set; }
        public Nullable<int> vida_actual { get; set; }
        public Nullable<int> mana_max { get; set; }
        public Nullable<int> mana_actual { get; set; }
        public Nullable<int> mon_estado { get; set; }
        public int id { get; set; }
    
        public virtual monstruos monstruos { get; set; }
        public virtual party_mon_cabecera party_mon_cabecera { get; set; }
        public virtual estado estado { get; set; }
    }
}
