//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class razas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public razas()
        {
            this.personajes = new HashSet<personajes>();
        }
    
        public int id_raza { get; set; }
        public string raza_nombre { get; set; }
        public Nullable<double> raza_fuerza { get; set; }
        public Nullable<double> raza_inteligencia { get; set; }
        public Nullable<double> raza_sabiduria { get; set; }
        public Nullable<double> raza_agilidad { get; set; }
        public Nullable<double> raza_resistencia { get; set; }
        public Nullable<double> raza_mult_vida { get; set; }
        public Nullable<double> raza_aspecto { get; set; }
        public Nullable<double> raza_afinidad_dioses { get; set; }
        public string raza_caracteristicas { get; set; }
        public string raza_atributos { get; set; }
        public string raza_imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personajes> personajes { get; set; }
    }
}
