//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public skill()
        {
            this.asoc_personaje_skill = new HashSet<asoc_personaje_skill>();
        }
    
        public int id_skill { get; set; }
        public string skill_nombre { get; set; }
        public Nullable<double> skill_nivel { get; set; }
        public string skill_tipo { get; set; }
        public string skill_atributo { get; set; }
        public Nullable<double> skill_costo { get; set; }
        public string skill_tipo_efecto { get; set; }
        public string skill_danio { get; set; }
        public string skill_dado_basico { get; set; }
        public string skill_requisito { get; set; }
        public string skill_alineamiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asoc_personaje_skill> asoc_personaje_skill { get; set; }
    }
}
